name: intel_hex
description: A Dart library that can read and write Intel HEX files. The Intel HEX format is a file format that contains binary information as ASCII text.
version: 1.2.1
repository: https://github.com/domohuhn/intel_hex
issue_tracker: https://github.com/domohuhn/intel_hex/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
